Catching Throwable instead of ClassNotFoundException because Class.forName can also throw LinkageError and ExceptionInInitializerError. If we silently ignore a ClassNotFoundException,  I don't see why we wouldn't ignore the others. A NoClassDefFoundError coming out of this method was causing my application to crash, but it was actually fine that the class couldn't be loaded.